### ISSUE TITLE
Import reorganisation requires upgrade of the major version

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio_tools#17]
Recent changes in the structure of the source code directories break old imports, e.g. if the user application installs `trexio-tools` package and calls some functions (e.g. `run-molden`) directly without passing by the `main` function. It's hard for me to say if we actually have users that use the tools like this.
The CLI is not affected.

**Comment by scemama** [comment]
The problem was that `converters` for example was a visible python module and could conflict with other namespaces of other packages. It is better to have it exposed as `trexio_tools.converters`.

**Comment by q-posev** [comment]
When installing with `pip install .`, the `converters` are not visible for me (Py 3.10):
```python
>>> from trexio_tools import converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'converters' from 'trexio_tools' (/home/q-posev/trexio_tools/src/trexio_tools/__init__.py)
>>> from trexio_tools.converters import convert_from
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'trexio_tools.converters'
```

I agree though that having Python packages under `src` is not Python-ic anymore. Modern packages have `module_name` folder in the root containing all Python sub-packages and modules for a given `module_name` Python software.

**Comment by q-posev** [comment]
I can do this when the PySCF converter is merged. However, there are some Git conflicts after recent reorganizations and I do not have time right now to fix them.
